# Generated by Django 4.1.7 on 2023-03-18 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jobapi.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("position", models.CharField(max_length=255)),
                ("job_location", models.CharField(max_length=255)),
                ("job_requirements_title", models.CharField(max_length=255)),
                ("job_requirements_body", models.TextField()),
                ("we_offer", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "jobs",
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("cover_letter", models.TextField()),
                (
                    "cv_upload",
                    models.FileField(
                        upload_to="applicant_cvs/",
                        validators=[jobapi.models.validate_file_extension],
                    ),
                ),
                ("salary", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobapi.jobs"
                    ),
                ),
            ],
            options={
                "db_table": "applicant",
            },
        ),
    ]
