# Generated by Django 4.1.7 on 2023-03-18 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("jobapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subcribers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
