# Generated by Django 4.1.7 on 2023-03-12 16:12

from django.db import migrations, models
import jobapi.models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="cv_upload",
            field=models.ImageField(
                upload_to="", validators=[jobapi.models.validate_file_extension]
            ),
        ),
    ]
