# Generated by Django 4.1.7 on 2023-03-18 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("jobapi", "0002_subcribers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Subcribers",
        ),
    ]
