# Generated by Django 4.1.7 on 2023-03-12 16:33

from django.db import migrations, models
import jobapi.models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapi", "0003_alter_applicant_cv_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="cv_upload",
            field=models.FileField(
                upload_to="applicant_cvs/",
                validators=[jobapi.models.validate_file_extension],
            ),
        ),
    ]
