# Generated by Django 4.1.7 on 2023-03-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobapi", "0004_alter_applicant_cv_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
